# Generated by Django 2.2.10 on 2020-03-29 18:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(blank=True, help_text='A subtitle to be displayed on the home page', max_length=250, null=True)),
                ('background_mask', models.CharField(blank=True, choices=[('d', 'Dark'), ('l', 'Light'), ('n', 'None')], help_text='Select semi-transparent mask to apply over background image.', max_length=1, null=True)),
                ('n_publications', models.IntegerField(default=5, help_text='The number of recent publications to return to the homepage.', verbose_name='Number of Recent Publications')),
                ('n_projects', models.IntegerField(default=5, help_text='The number of recent projects to return to the homepage.', verbose_name='Number of Recent Projects')),
                ('n_blog_posts', models.IntegerField(default=5, help_text='The number of recent blog posts to return to the homepage.', verbose_name='Number of Recent Blog Posts')),
                ('background_image', models.ForeignKey(blank=True, help_text='Apply an image to the background', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePageCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('text_orient', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=20, null=True)),
                ('carousel_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
